#!/usr/bin/env python
# -*- coding: utf-8 -*-

from subprocess import call
import requests, sys, json

USER = 'YOURUSERNAME' # Change this to your Fileslap username
PASS = 'YOURPASSWORD' # Change this to your Fileslap password

r = requests.post('http://fileslap.com/api/files/', files={'file': open(sys.argv[1])}, auth=(USER, PASS))

if (r.status_code is not 200):
    try:
        print "Error " + str(r.status_code) + ": " + r.content
    except TypeError: # r.content may throw a type error 
        print "Error " + str(r.status_code)
    sys.exit()
        
data = json.loads(r.content)
print "URL: http://fileslap.com" + data['url']
print "Raw: " + data['fileurl']
